version: "3"

services:
  backend:
    image: asyncdeveloper/grammar-check-backend:latest
    ports:
      - "3000:3000"
    networks:
      - hng-internal
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=127.0.0.1
      - DATABASE_URI_DEVELOP=mongodb://localhost:27017/grammerly
      - DATABASE_URI_PROD=
      - DATABASE_URI_TEST=mongodb://localhost:27017/
      - CLIENT_ID=978033281049-hrkp6grkg6mo2cmm2rc9vkvvbr0722ls.apps.googleusercontent.com
      - CLIENT_SECRET=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
      - SERVER_ROOT_URI=http://localhost:5000
      - LINKEDIN_SECRET_ID=4QAmvQlLTao6DAmV
      - LINKEDIN_CLIENT_ID=77bvokl0d80r4u
      - CALLBACK_URL=http://localhost:5000/api/v1/linkedin/callback
      - OPENAI_API_KEY=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
      - SESSION_SECRET=this is randoo
      - JWT_SECRET=thisiswhole
      - JWT_OPTION=24hr
      - FB_CLIENT_ID=468368708698228
      - FB_CLIENT_SERECT=b5e329203566deb6061247dd8272a67b
      - FB_CALLBACK_URL=http://localhost:3000/auth/facebook/callback
      - MODEL_KEY=c8aa6761-7acd-4ffc-abc9-080a9ffe6708
      - API_KEY=c5d2f9b9-9869-41be-bd24-e274452504cf
      - FILE_SIZE=104857
  frontend:
    image: asyncdeveloper/grammar-check-frontend:latest
    ports:
      - "5000:5000"
    networks:
      - hng-internal
    restart: always

networks:
  hng-internal:
