version: "3"

services:
  backend:
    image: asyncdeveloper/grammar-check-backend
    ports:
      - "3000:3000"
    networks:
      - hng-internal
  frontend:
    image: asyncdeveloper/grammar-check-frontend
    ports:
      - "5000:5000"
    networks:
      - hng-internal
    depends_on:
      - backend

networks:
  hng-internal:
